name: C/C++ debug arm macos

on:
  push:
    branches:
      - Nigthly
      - Nightly

jobs:
  build:

    runs-on: macos-11
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'Nigthly'
    - name: build deps & slicer
      run: ./BuildMacOS.sh -ia
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos_arm.dmg
        path: build/SuperSlicerVertex.dmg
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos_arm.tar
        path: build/SuperSlicerVertex.tar
