name: C/C++ Nigthly ubuntu

on:
  push:
    branches:
      - Nigthly
      - Nightly

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'Nigthly'
    - name: update submodule profiles
      working-directory: ./resources/profiles
      run: git submodule update --init
    - name: change date in version
      run: sed -i "s/+UNKNOWN/_$(date '+%F')/" version.inc
    - name: update clock
      run: sudo hwclock -s
    - name: update apt
      run: sudo apt update
    - name: install gtk2 glew
      run: sudo apt install libgtk2.0-dev libglew-dev libudev-dev libdbus-1-dev
    - name: build deps & slicer
      run: ./BuildLinux.sh -dgs
    - name: make .pot
      working-directory: ./build
      run: make gettext_make_pot
    - name: build tar & appimage
      working-directory: ./build
      run: src/BuildLinuxImage.sh -i
    - name: ls /home/runner/work/SuperSlicer-VERTEX-Edition
      run: ls /home/runner/work/SuperSlicer-VERTEX-Edition
    - name: ls /home/runner/work/SuperSlicer-VERTEX-Edition/SuperSlicer-VERTEX-Edition
      run: ls /home/runner/work/SuperSlicer-VERTEX-Edition/SuperSlicer-VERTEX-Edition
    - name: ls /home/runner/work/SuperSlicer-VERTEX-Edition/SuperSlicer-VERTEX-Edition/build
      run: ls /home/runner/work/SuperSlicer-VERTEX-Edition/SuperSlicer-VERTEX-Edition/build
    - name: ls /home/runner/work/SuperSlicer-VERTEX-Edition/SuperSlicer-VERTEX-Edition/build/package
      run: ls /home/runner/work/SuperSlicer-VERTEX-Edition/SuperSlicer-VERTEX-Edition/build/package
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_linux_gtk2.tar
        path: build/SuperSlicerVertex.tar
    - name: Upload appimage
      uses: actions/upload-artifact@v1.0.0
      with:
        name: SuperSlicerVertex-gtk2.AppImage
        path: build/SuperSlicerVertex_ubu64.AppImage
